name: qr_code_wallet
description: An application to save QR codes.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0 < 4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:
  qr_flutter:
  mobile_scanner:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
