name: qr_code_wallet
description: An application to save QR codes.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0 < 4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  qr_flutter:
  mobile_scanner:
  flutter_riverpod:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  arb_generator:

flutter:
  uses-material-design: true
  generate: true

arb_generator:
  input_filepath: "assets_dev/loca/loca.csv"
  output_directory: "assets_dev/l10n"
  filename_prepend: "l10n_"
  csv_settings:
    delimiter: ";"
    base_index: 1
