name: qr_code_wallet
description: An application to save QR codes.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.27.0 < 4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  go_router:
  qr_flutter:
  mobile_scanner:
  path_provider:
  isar: ^4.0.0-dev.14
  # https://github.com/isar/isar/issues/1647
  isar_flutter_libs:
    git:
      url: https://github.com/realth000/isar/
      ref: 98a6cc1236498ce79a9096f772da754df838da0c
      path: packages/isar_flutter_libs
  hive: ^4.0.0-dev.2
  flutter_riverpod:
  riverpod_annotation:
  gap:
  url_launcher:
  share_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  arb_generator:
  riverpod_generator:
  flutter_launcher_icons:
  app_store_screenshots:
    git: https://github.com/defuncart/app_store_screenshots
  mocktail:
  custom_lint:
  riverpod_lint:

flutter:
  uses-material-design: true
  generate: true

arb_generator:
  input_filepath: "assets_dev/loca/loca.csv"
  output_directory: "assets_dev/l10n"
  filename_prepend: "l10n_"
  csv_settings:
    delimiter: ";"
    base_index: 1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets_dev/app_icons/app_icon.png"
  adaptive_icon_background: "#FFC107"
  adaptive_icon_foreground: "assets_dev/app_icons/android_icon_foreground.png"
