name: qr_code_wallet
description: An application to save QR codes.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0 < 4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  go_router:
  qr_flutter:
  mobile_scanner:
  path_provider:
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
  hive: ^4.0.0-dev.2
  flutter_riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3
  gap:
  url_launcher:
  share_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner:
  arb_generator:
  riverpod_generator: ^3.0.0-dev.11
  flutter_launcher_icons:
  app_store_screenshots:
    git: https://github.com/defuncart/app_store_screenshots

flutter:
  uses-material-design: true
  generate: true

arb_generator:
  input_filepath: "assets_dev/loca/loca.csv"
  output_directory: "assets_dev/l10n"
  filename_prepend: "l10n_"
  csv_settings:
    delimiter: ";"
    base_index: 1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets_dev/app_icons/app_icon.png"
  adaptive_icon_background: "#00BCD4"
  adaptive_icon_foreground: "assets_dev/app_icons/android_icon_foreground.png"
