name: ci_pull_request
on: pull_request
jobs:
  lint-unit-test:
    name: Lint + Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      - name: Generate localization files
        run: dart run arb_generator
      - name: Install packages
        run: flutter pub get
      - name: Lint
        run: flutter analyze
      - name: Tests
        run: flutter test --exclude-tags app_store_screenshots
